services:
  - type: web
    name: bmu-xlsx-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_CREDENTIALS
        value: <ВСТАВИШЬ_ЗДЕСЬ_JSON_В_КАВЫЧКАХ>
